# Generated by Django 4.1.2 on 2022-10-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('movement', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
