# Generated by Django 4.1.2 on 2022-10-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_rename_cat_service_watch_alter_service_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='watch',
            name='straps',
            field=models.ManyToManyField(to='main_app.strap'),
        ),
    ]
